name: MaSuite
version: 1.0.0
main: dev.masa.masuite.paper.MaSuitePaper
api-version: 1.17
authors: [ Masa ]
description: Proxy wide homes, teleportations and warps
website: https://masa.dev
permissions:
  masuite.home.user:
    description: Basic user permissions for Homes
    children:
      masuite.home.set: true
      masuite.home.delete: true
      masuite.home.teleport: true
      masuite.home.list: true
  masuite.home.staff:
    description: Staff permissions for Homes
    children:
      masuite.home.set.others: true
      masuite.home.delete.others: true
      masuite.home.teleport.others: true
      masuite.home.list.others: true
      masuite.home.warmup.bypass: true
      masuite.home.cooldown.bypass: true

  masuite.warp.user:
    description: User permissions for Warps
    children:
      masuite.warp.list: true
      masuite.warp.list.global: true
      masuite.warp.list.server: true
      masuite.warp.teleport: true

  masuite.warp.staff:
    description: Staff permissions for Warps
    children:
      masuite.warp.list.hidden: true
      masuite.warp.delete: true
      masuite.warp.set: true
      masuite.warp.warmup.bypass: true
      masuite.warp.cooldown.bypass: true

  masuite.teleport.user:
    description: User permissions for Teleport
    children:
      masuite.teleport.request.to: true
      masuite.teleport.request.here: true
      masuite.teleport.request.accept: true
      masuite.teleport.request.deny: true
      masuite.teleport.request.lock: true
  masuite.teleport.staff:
    description: Staff permissions for Teleport
    children:
      masuite.teleport.all: true
      masuite.teleport.player: true
      masuite.teleport.player.others: true
      masuite.teleport.player.here: true
      masuite.teleport.location: true
      masuite.teleport.location.others: true
      masuite.teleport.warmup.bypass: true
      masuite.teleport.cooldown.bypass: true